server:
  port: 8181
spring:
  datasource:
    username: root
    password: 556677
    url: jdbc:mysql://localhost:3306/vueBook?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis: 39.106.161.181

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true




